### ISSUE TITLE
support for Energy Management (WHO=18)

### ISSUE THREAD

**Issue by enrico-cc** [mvalla/openhab2-addons#11]
it would be nice to support the readings of power consumption

`e.g. frame=*#18*51*113*1253##`

thanks,
Enrico

**Comment by llegovich** [comment]
+1 for energy management

**Comment by mvalla** [comment]
closed in release beta9-1

**Comment by gabrieledaltoe** [comment]
Can I use beta9 with bticino F520 ?

**Comment by AlessandroLacroce** [comment]
Hi, I'm trying to use beta9-2 with my bticino (I also have one 521 and 4 523) but it seems that the auto discovery it's not working and, if I add it manually, I receive an "OFFLINE - COMMUNICATION_ERROR". Is there anything I need to do in order to make it work?

The manual configuration is done like this: 
![schermata 2019-02-01 alle 13 52 09](https://user-images.githubusercontent.com/1499430/52124250-f0ae1a80-2628-11e9-8847-5963ecccf01c.png)

After this I receive: 

![schermata 2019-02-01 alle 13 53 55](https://user-images.githubusercontent.com/1499430/52124260-fa378280-2628-11e9-8365-770360db8db9.png)

Any hints? 

Thanks

**Comment by mvalla** [comment]
@alessandrolacroce follow the test of my first comment using the official OpenWebNet client for BTcino to see if your device is discoverable in the BUS. And also you should see periodically event messages stattting with *18* that indicate a new power measurement . Post the result of he test here.

**Comment by AlessandroLacroce** [comment]
Ok, here are the results of the test:

![schermata 2019-02-01 alle 19 07 59](https://user-images.githubusercontent.com/1499430/52141046-d12ce700-2654-11e9-8729-6ba073c811f8.png)

And this: 

![schermata 2019-02-01 alle 19 08 24](https://user-images.githubusercontent.com/1499430/52141061-dd18a900-2654-11e9-9553-5ce6add34b11.png)

While this is the output of the log viewer if I search for "18"

![schermata 2019-02-01 alle 19 09 50](https://user-images.githubusercontent.com/1499430/52141107-076a6680-2655-11e9-9c47-1a895cae1435.png)

Hope it helps
