### ISSUE TITLE
thermo: activeMode displays only the state “Off" and "anti freeze”

### ISSUE THREAD

**Issue by mvalla** [mvalla/openhab2-addons#46]
reported by some users: 
thermo activeMode displays only the state “Off" and "anti freeze” not the state “auto" or manual”

https://community.openhab.org/t/bticino-openwebnet-new-openhab2-binding-ready-for-testing/43377/376?u=massi

**Comment by mvalla** [comment]
relevant and well formatted log when this happens is needed by someone experiencing this

**Comment by weltraumbagger** [comment]
massimo, 
for me it seems this issue is solved, active mode always shows the correct state!

the only thing i want to remark is that already known discussion how to procceed with new variables. als i work a lot with "visibility" in sitemap especially for thermo as you can see [here](url) this does not work from beginning (as long as values are NULL or UNDEF)

i would like to have the possibillity to init the state for new items and at restart

**Comment by mvalla** [comment]
reported as solved by beta9-2
