### ISSUE TITLE
Update tags for homekit

### ISSUE THREAD

**Issue by Gozilla01** [mvalla/openhab2-addons#73]
[There](https://github.com/openhab/openhab2-addons/pull/5082) is a very strong PR for Homekit.
Inside there are several name tags changes.
[Link](https://github.com/hap-java/openhab2-addons/tree/homekit/addons/io/org.openhab.io.homekit) documentation
Evaluate the changes.

**Comment by mvalla** [comment]
Can you list here which exactly new tags or existing tags will be changed?
Is the change valid for all assistants or only for HomeKit ?
The binding should more properly use tags that are part of the ESH Ontology & Semantic Tags proposal (see: https://community.openhab.org/t/habot-walkthrough-2-n-semantic-tagging-item-resolving/55651) 
Otherwise if tags are added that are valid only for a specific Assitant addon, the other assistants will not work anymore
M

**Comment by Gozilla01** [comment]
Yes you are right
I opened the issue to get a reminder
We will see down ahead
