### ISSUE TITLE
The release 2.5.0 m2 could be expired?

### ISSUE THREAD

**Issue by andrea-parisi** [mvalla/openhab2-addons#93]
Hi @mvalla, I was using the milestone release m2 of openhab until yesterday morning, when I upgraded my system to openhab m3. For a few hours it all seemed fine but by the afternoon he suddenly stopped working. Now in the the log I can find this error:

> 14:12:48.967 [ERROR] [org.openwebnet.AbstractOpenGateway   ] - ERROR IN Java $MODULE$: connection cannot be established

I thought to downgrade openhab but the error is always the same. it may be inherent in the expired release of the binding?

## Your Environment

* Version used: Openhab 2.5.0-m1 and 2.5.0-m3
* Environment name and version openhab2-addons 2.5.0-m2
* Operating System and version Raspbian Buster (on Raspberry Pi 4)

**Comment by mvalla** [comment]
yes, the 2.5.0.M2 version is expired now.

Working already on a 2.5.0.M3 but in these hours I face problems with Eclipse and the development environment (as is happening since few months now to all OH2 developers, [see here](https://github.com/openhab/openhab-distro/issues/927)).

**Comment by andrea-parisi** [comment]
Thanks @mvalla. I await the next release.

Regards.

**Comment by fmalfatto** [comment]
So you guys are telling that an application can be stopped in its developments and freezed since months due to a change to development environment? I worked on Operating Systems since 1980 and never saw this event. Ah, but Java was not yet arrived. I always forget this small detail ... :-)

**Comment by mvalla** [comment]
> So you guys are telling that an application can be stopped in its developments and freezed since months due to a change to development environment?

It has not been compeltely freezed, but the new dev environment (which clearly was not tested before starting the transition of the whole project) has created big difficulties for many using Eclipse, including developer of important bindings like Zigbee and Zwave with huge expertise in java. 
It's also a matter of time: since everyone works on this project in his spare time (maybe few hours a week), if you waste this time in migrating/setting up the new dev environament, which now brakes often, then development slows down a lot.
I would not balme Java, instead it's the combination of Eclipse+maven+OSGi+bndtools that does not work well and is unstable. 
Listen [carefully to this video](https://www.youtube.com/watch?v=92szjGgt0SY) to understand what were the options (btw Kai has stepped down from project lead...)

**Comment by mvalla** [comment]
new release: [own-2.5.0.M3](https://github.com/mvalla/openhab2-addons/releases/tag/own-2.5.0.M3)
